logging:
  level:
    root: info
    com: debug

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://185.233.187.160:3306/default_db
    username: gen_user
    password: Ah6Ma7[\+BX8&U
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    check-template-location: false
server:
  port: 8081